### ISSUE TITLE
asset-hash depends on node-xxhash that is not used by default and is not maintained anymore

### ISSUE THREAD

**Issue by sormy** [sebastian-software/asset-hash#1]
Hello.

asset-hash depends on node-xxhash that is not used by default and is not maintained anymore.
See this PR as an example: https://github.com/mscdex/node-xxhash/pull/25

1. I propose to move "xxhash" into "optionalDependencies", conditionally check if it is loaded from "asset-hash" and use it if available and throw an exception if xxhash hashing method is used.

2. Another option is to switch to xxhashjs that is the same I guess but pure JS.

3. Last option is to support both xxhash and xxhashjs and use one of them dependending on what is installed, also put both of them to peerDependencies.

This change will require major version bump I guess but I would like to update just minor to not break compatiblity with postcss-smart-asset. Another good option is to bump major for both (since you own both).

Would you be open for PR and what solution would you prefer?

**Comment by swernerx** [comment]
Hi! thanks for reporting. I actually never had this issue nor none of my colleagues (Mac, Windows + Gitlab CI). I figure it makes sense to move it to optional dependencies and checking the availability. Please create the PR for this. Thanks a lot.

**Comment by swernerx** [comment]
Fixed with v2.3.0.
