### ISSUE TITLE
Is there an option to make metrohash dependency optional?

### ISSUE THREAD

**Issue by zhaparoff** [sebastian-software/asset-hash#3]
Although I can agree that `metrohash` library is one of the best choices from performance perspective, it requires Python and C++ toolchain to be installed. Meanwhile, modern C++ Build Tools for Windows require over 5 GB for installation and they should be set up on every worksatation that is used for building project that depends on asset-hash. 

Thus, it would be nice to have `metrohash` dependency as optional, with fallback to standard Node hashing, for example. At least when using hashing in tools, where performance is not a primary concern.

Initial issue: sormy/rollup-plugin-smart-asset#2

**Comment by zhaparoff** [comment]
sormy/rollup-plugin-smart-asset#2

**Comment by swernerx** [comment]
There is unfortunately no easy way for optional dependencies with node packages. I see that it can be cumbersome to have native extensions on Windows, but once installed it's helpful for various packages e.g. express middlewares, ...
